print("Q: How to check a variable's type?")
print("A: we use type() function")
print()
print("Q: in what cases, you will get SyntaxError from the compiler telling you that some of your variables have invalid names? Can you give 3 different examples of invalid names?")
print("A: names which start with a number, or contain an illegal character such as $ or ., or randomly are one of 29 keywords are illegal and will give SyntaxError")
print("for examples: 8frankie, ty$ or exec")